DB設計
TechCafeFreedom/Wantum-server pull request #15
Opened 2020-07-20 08:02 UTC by akubi0w1

## Issue
close  #5 

## 概要
アプリケーションのDB設計と、DDL、サンプルデータの用意

## タスク整理
- [ ] 設計
- [ ] ddl
- [ ] サンプルデータの用意
- [ ] dml

## 変更内容

## 動作確認方法
mysqlサーバを立てて、
`mysql -h {host} -u {user} -p{password}  -e "source ~/path/to/ddl.sql or dml.sql"`で実行可能。

## 補足事項
Issue #8 でDB環境など整えるので、動作確認方法の記載、READMEへの追記などは、そちらで真面目にやります。

2020-07-20 18:10 UTC, TakumaKurosawa requested changes
コメントしました！

2020-07-20 18:10 UTC, TakumaKurosawa commented on mysql/init.d/dml.sql
> +use wantum;
SEEDまで作ってくれて本当ありがとう！！！

2020-07-20 18:10 UTC, TakumaKurosawa commented on mysql/init.d/ddl.sql
> +);
placesとtagsテーブルはwish_cardと繋がりが深い項目やと思うから、 特に理由がなければwish_cardsとalbumsの間に移動してほしいっす！

2020-07-20 18:10 UTC, TakumaKurosawa commented on mysql/init.d/ddl.sql
> +  bio varchar(100) NOT NULL,
[確認]bioって「ひとことプロフィール」みたいな物だと思っておけばOK？

2020-07-20 18:10 UTC, TakumaKurosawa commented on mysql/init.d/ddl.sql
> +  place varchar(30) NOT NULL,
プロフィールでいうところのPlaceってどういう役割を持つんだっけ？？

2020-07-20 18:10 UTC, TakumaKurosawa commented on mysql/init.d/ddl.sql
> +  birth date NOT NULL,
Google認証などでアカウントを作った場合にはBirthDay情報などはないので、NULL制約つけなくて良いと思った

2020-07-20 18:10 UTC, TakumaKurosawa commented on mysql/init.d/ddl.sql
> +  phone varchar(15) NOT NULL,
Google認証などでアカウントを作った場合にはPhone情報などはないので、NULL制約つけなくて良いと思った

2020-07-20 18:10 UTC, TakumaKurosawa commented on mysql/init.d/ddl.sql
> +  gender int NOT NULL COMMENT '1=man, 2=woman, 3=other',
Google認証などでアカウントを作った場合にはgender情報などはないので、NULL制約つけなくて良いと思った

2020-07-20 18:10 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  image_url varchar(2048) NOT NULL,
imageだとなんの画像か分かりづらいので、background_imageとかにした方が良いのかなー？

2020-07-20 18:10 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  user_id int NOT NULL,
これはカテゴリーを作成したユーザを特定するためにあるのかな？？
カテゴリーは誰が作成したかを知らなくてもそんなに困らなそう。

2020-07-20 18:10 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  activity varchar(50) NOT NULL,
Commentで良いので、「〇〇で××する」みたいなフォーマットってことを明記しておいてもらえるとありがたい！

2020-07-20 18:10 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  user_id int NOT NULL,
wish_cardsに関しては誰が作ったかという情報があっても良いと思う。（この実装で良さそう。）

2020-07-20 18:10 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  place_id int NOT NULL,
外部キー制約の記述がなさそう！

2020-07-22 01:06 UTC, akubi0w1 reviewed
めっちゃ細かいとこまで見てくれてありがとうです！修正しておきます！！！

2020-07-22 01:06 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  bio varchar(100) NOT NULL,
そう！他サービスだと、自己紹介とかって書いてあるとこのイメージ。

2020-07-22 01:06 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  gender int NOT NULL COMMENT '1=man, 2=woman, 3=other',
profileに関してはNULL活かせるところはありそうだなーて思うんだけど、goの性質上、取得したカラムのマッピングでぬるぽ吐かれるから、基本的に`NOT NULL`でつけてます！
nullいけたっけ？と思い始めたから検証します( ˘ω˘ )

2020-07-22 01:06 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  phone varchar(15) NOT NULL,
genderのとこと一緒な感じです！

2020-07-22 01:06 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  place varchar(30) NOT NULL,
ついったでいう、ユーザの現在地、みたいなフィールドです( ˘ω˘ )

2020-07-22 01:06 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  birth date NOT NULL,
genderのとこと同じ感じ！です！

2020-07-22 01:06 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  image_url varchar(2048) NOT NULL,
やっぱそうよなwww
background要素は普通に入れたいよね...ただURLであることは明示しておきたいので、`background_image_url`にするかも

2020-07-22 01:06 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  user_id int NOT NULL,
そうー！確かにカテゴリに関してはそこまで必要じゃないんよな。
修正しておきます！

2020-07-22 01:06 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  activity varchar(50) NOT NULL,
おけい！コメント挟んでおきます！

2020-07-22 01:06 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  place_id int NOT NULL,
ここは`place_id`のフィールドの消し忘れだわ。。。。
albumsにplaceフィールドいらんって感じになってたの、消し忘れた感じです。。。

2020-07-22 01:22 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +);
これ、wish_cardsより前にtagsとplacesを定義しておかないと、クエリ実行したときにエラー出るんよね。
FKつけようとしたけど、そのフィールドないよって言われてしまうんよ。だから結構上においてある感じなんよ。
できる限り下に移動することはできるんで、そうしておくわ！
ただこれ対処法あるかもしれないから調べておきます！

2020-07-22 05:28 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +);
これ対処できたわ！
place, tagsはそれぞれ下方に移動させておきます！

2020-07-22 07:07 UTC, sana37 commented on mysql/init.d/ddl.sql
> +  	FOREIGN KEY (id)
ここはuser_idかな？

2020-07-22 07:11 UTC, sana37 commented on mysql/init.d/ddl.sql
> +  invite_url varchar(2048) NOT NULL,
esaの方には書いてあったUNIQUE制約はなくしたってことでおｋ？
できるだけインデックス減らすっていう意味ではたしかに良さそう

2020-07-22 07:24 UTC, sana37 commented on mysql/init.d/ddl.sql
> +  description varchar(100) NOT NULL,
wish_cards::descriptionについてもそうなんだけど、もうちょい文字数に余裕を持っても損はないんじゃないかな、て思った！
例えば、256とか

2020-07-24 09:29 UTC, sana37 commented on mysql/init.d/ddl.sql
> +  date datetime NOT NULL,
datetimeじゃなくてdateがいいと個人的に思ってる。
ユーザは細かい時間とかまで入力したくないんじゃないかな

2020-07-25 12:57 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +);
あざす！

2020-07-25 13:00 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  bio varchar(100) NOT NULL,
```suggestion
  bio varchar(100) NOT NULL comment 'ひとこと自己紹介',
```

2020-07-25 13:02 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  gender int NOT NULL COMMENT '1=man, 2=woman, 3=other',
Slackで会話した通り、基本的にはNOT NULL制約つけましょう！
https://wantum.slack.com/archives/C0164MEN679/p1595402334003800

2020-07-25 13:04 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  image_url varchar(2048) NOT NULL,
良さそう！

2020-07-25 13:07 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  invite_url varchar(2048) NOT NULL,
@sana37 
@akubi0w1 
個人的にはUNIQUEは有って欲しいかなー。。。
確かに一意にしたいという意味合いでは、サーバの実装側でUIDとか使っちゃえば問題ないんだけど、`invite_url`で検索をかけたときに検索にめちゃくちゃコストかかるのが心配。
多分リストとかの数が膨大になればなるほど、検索にかかる時間が指数関数的に増加しそう。

2020-07-25 13:10 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  date datetime NOT NULL,
@sana37 
確かに時間まで含めたいって人少なそうだよね。
ただ、将来的に人と共有できるスケジュール帳として使うという用途にも対応できたら嬉しいので、変に拡張性を削るよりは、datetime型にしておいて、Time以降は基本的に `00:00:00`みたいな感じにすれば良さそうじゃないかな？

2020-07-25 13:11 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  place_id int NOT NULL,
OK!

2020-07-25 13:12 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  description varchar(100) NOT NULL,
確かにねー。
それこそ、ここをマークダウンとかでメモできるみたいにしたくなったら余裕で500文字とか書きそうだもんな。

2020-07-26 02:08 UTC, sana37 commented on mysql/init.d/ddl.sql
> +  invite_url varchar(2048) NOT NULL,
wish_listの招待URLなんだけど、
`wishlists/{wish_list_id}/join/{invite_id}`
みたいな構成にしようと思ってるから、`invite_url`で検索かけることはなさそう。
wish_list_idで検索してから、`invite_url`が正しいかチェックする感じ

2020-07-26 02:15 UTC, sana37 commented on mysql/init.d/ddl.sql
> +  date datetime NOT NULL,
あー、実装でカバーすればいっか。
じゃあ、こっちの話になってしまって済まないんだけど、APIのレスポンスではdate型で返す（サーバがdatetime -> dateの変換を行う）でいいかな？

2020-07-26 12:49 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  date datetime NOT NULL,
@sana37 
いや、サーバ側で時間を切り捨てるみたいな実装は無理にする必要はなくって、クライアント側で表示する時だけDateまでの情報を表示してもらえば良さそう。

どちらにせよ、クライアント側とUNIXTIME使うのか、UTC使うのかとか決めておいた方が良さそう。

2020-07-26 12:51 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  invite_url varchar(2048) NOT NULL,
なるほど、その設計なら確かにいらなさそうやね！
勝手なイメージで、invite_urlにはURLが入ると思っていた！

2020-07-27 00:55 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  	FOREIGN KEY (id)
ほんとや。。。。！修正します、、、！

2020-07-27 01:01 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  invite_url varchar(2048) NOT NULL,
@Takumaron @sana37
invite_urlで普通にURL突っ込むことを想定していた！
利用者的には、invite_urlを踏むことで、参加APIに転送なりするイメージだったんよね。

uniqueは了解！です！

さなくんの感じでいくと、invite_idってフィールドが必要になる感じ？

2020-07-27 01:03 UTC, akubi0w1 commented on mysql/init.d/ddl.sql
> +  description varchar(100) NOT NULL,
そうやねえー！確かに。
256とかだと、利用者側にあんま馴染みないかもしれないから、500で揃えておきます！

2020-07-27 06:37 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  invite_url varchar(2048) NOT NULL,
@sana37 
@akubi0w1 
この招待リンクについては一旦保留しようか！実際にこの機能を実装するときに議論しよう！👍

2020-07-27 06:39 UTC, Takumaron commented on mysql/init.d/ddl.sql
> +  date datetime NOT NULL,
こちらフロントと話し合って、UTCに決まりました。
そのため、サーバの実装側でJST→UTCなどの処理が必要になります。
@akubi0w1 
@sana37

2020-07-27 11:35 UTC, akubi0w1 commented
レビューあってから、修正しましたー！確認お願いします！

 ## 変更点

- ddl時のFK作成チェックを外す
- 一部カラムにコメントを追加
- wish_lists.image_url -> wish_lists.background_image_url
- wish_cards.description, memories.descriptionの文字数を100 -> 500に変更。

birthのデフォルト値について
dateフィールドにデフォルト値が存在しないので、NULLを入れています。ここだけサーバの実装でNULL回避する必要がありそう。

invite_urlのuniqueについて
charsetを`utf8mb4`にすると、`varchar(1)`としたとき、最大で4バイト(一文字分のバイト数)が確保されます。
URLの最大長(2048)にした場合、確保するバイト数が8192バイトになります。MySQLでは、キーにできる最大長が3072バイトらしく、このフィールドでは超過してしまいます。そのため、UNIQUE制約をつけていません。

2020-07-30 12:53 UTC, TakumaKurosawa approved these changes
OK! LGTMです！
もしコードフォーマッターとか使っているエディタにあったらフォーマットかけてからマージしてもらえると嬉しいです！

2020-07-30 14:51 UTC, merged