APIドキュメントの作成 #6
TechCafeFreedom/Wantum-server pull request #16
Opened 2020-07-20 13:21 UTC by sana37

## Issue
* #6 

## 概要
* stoplightを用いたAPIドキュメントの作成

## 補足
* OpenAPI 3.0.0 を利用
* ver1で必要なAPIのみ定義

### APIドキュメント閲覧用URL
* https://stoplight.io/p/docs/gh/techcafefreedom/wantum-server

### mockサーバのURL
* https://stoplight.io/p/mocks/13862/146524/
  * ↑このURLに各APIのパスを足して利用してください

2020-07-20 13:44 UTC, sana37 commented
@Takumaron 
> StoplightってHeaderの定義とかってできなかったっけ？もしできるなら、BearerTokenが必要なAPIにはつけて欲しい！
* 了解！

> SignUpについては、一旦Google認証だけやと思うからBodyは空で良い気がしている
> Profile新規作成APIあると思うんだけど、これは本来SignUpに含まれるべきAPIだと思っていて、SignUp以降は情報の更新APIになるんじゃないかなと思う。
* たしかに、signupの時点でprofileも同時に作成されてなきゃ困るからそうしよっか。profile単体の新規作成APIはいらないね
* となると、signupのbodyにprofileのパラメータ入れたくなる…

> アルバムUpdateでメンバー情報を送って恐らくメンバーの追加も表現していると思うんだけど、できればメンバー招待系は別APIに切り出したい。
* そうする！汎用的すぎるAPIってクライアント側に優しくなさそうだわ！

> できたらでイイんだけど、各APIのタイトルを日本語で具体的に何をするのか分かるように書いて欲しい！（もし日本語使えなさそうなら英語で具体的に処理の説明を書いて欲しい）
* 了解！

2020-07-20 14:38 UTC, sana37 commented
@akubi0w1 
> profilesとusers分けなくてもいいかなって思った
* なるほど！思考停止でモデルごとに作っちゃってた！自分としても分けないほうがいいと思ったからくっつける！

> 500があったほうがいいと思う！
* 仕様としてはあっちゃいけないエラーだから書かなくていっか、て思っちゃった

> delete関連のレスポンスは、204でもいいかも？返すコンテンツが何もないことをステータスコードで明示できるので。200でもいいと思う！
* クライアント側で `if (statusCode == 200)` みたいな使い方することを考慮して、200にしようかな〜

> 日付フォーマットどうしよう？
* 決めなければ！`yyyy/mm/dd hh:mm:ss`にするね

> ヘッダ設定できたりせんかな...？と思ってる。Authヘッダにアクセストークン乗せてねって書きたい気がする！
* やっておく！

> bodyは以下のがいいかも？
> {
>   "title": string,
> }
* 了解！

> `/albums/{album_id}/join`みたいなエンドポイント作って、そこにリクエストしてきた人をメンバーに追加するっていうほうがいいのかな？と。なんでかというと、membersのarrayを毎回完璧に作る感じになるかもしれないので、アプデの際に漏れとかミスがおこっちゃうかなって思うんですよ…。
* まさしくそのとおりだわ、、直します！wish_listについても同様に！

>  memory timeline
> - レスポンスで異常系がないのってなにか理由ある感じ？
* これなんだけど、
  * anonymousでも使える
  * リクエストbodyがない

って考えると予想可能なエラーって存在しないのでは？と思った。
今きづいたけど、paging用のパラメータ必要だわ。

> サインイン(ログイン処理)は多分クライアント-firebase間で完結した気がする？
* JWTが変更されたときに、`auth_id`を更新する必要があるんじゃないかな？

> sign up
> - ここにjwt乗せて欲しいかも
* 了解！

2020-07-20 18:13 UTC, Takumaron commented
`close #6`でプルリクがマージされたタイミングで #6 がCloseするようにできるよ！

2020-07-20 18:15 UTC, TakumaKurosawa requested changes
一旦 @sana37 がConversationに書いてくれているコメントたちをレビューとしたいです。

2020-07-22 00:54 UTC, akubi0w1 requested changes
レビューの返信でいくつか！

>>サインイン(ログイン処理)は多分クライアント-firebase間で完結した気がする？

> JWTが変更されたときに、auth_idを更新する必要があるんじゃないかな？

auth_idはJWTが更新されても変わらないはず？firebaseで管理されているuidなので！

---

>> memory timeline
>> レスポンスで異常系がないのってなにか理由ある感じ？

>これなんだけど、
anonymousでも使える
リクエストbodyがない
って考えると予想可能なエラーって存在しないのでは？と思った。
今きづいたけど、paging用のパラメータ必要だわ。

たしかになさそう、、、！なるほど！
pagingは確かに！クエリとかで挟み込む必要ありそう！

---

>> 500があったほうがいいと思う！

> 仕様としてはあっちゃいけないエラーだから書かなくていっか、て思っちゃった

サーバのエラーが起きときに、クライアントのエラーってレスポンスするのはやばそうなので、あったほうがいいと思うんよな。
トランザクションとかでエラー吐かれたときに、クライアントに正しく通知するために必要かなーと。
確かにあっちゃいけないんだけどね( ˘ω˘ )

あと、これはくろちゃんのレビューの方なんやが、
signup、profileの作成は、signupにひとまとめにしなくてもいいかなーと。
signup時に、profileに全て初期値とかでレコード作っておいて、profileの内容が登録され次第、随時更新でもいいのかなーって思った。
ただこの方法だと、クライアント側がめんどくさいかなーって思ったり。悩みどころ( ˘ω˘ )

2020-07-22 07:54 UTC, sana37 commented
@akubi0w1 
> auth_idはJWTが更新されても変わらないはず？firebaseで管理されているuidなので！
* あ、まじか！じゃあサインインはいらないね〜

> サーバのエラーが起きときに、クライアントのエラーってレスポンスするのはやばそうなので、あったほうがいいと思うんよな。トランザクションとかでエラー吐かれたときに、クライアントに正しく通知するために必要かなーと。
* 仕様書を通して、500も起こりうるよって認識を与えるためにも、書いた方がいいか。足しときます！

> signup、profileの作成は、signupにひとまとめにしなくてもいいかなーと。
signup時に、profileに全て初期値とかでレコード作っておいて、profileの内容が登録され次第、随時更新でもいいのかなーって思った。
* 初期値つっこんどけばいっか。たしかに、ユーザにひととおり情報入力させたあとに、signup失敗ですやり直してくださいとか返ってきたらキレそうだ…

2020-07-23 03:07 UTC, ho2ri2s commented
> たしかに、ユーザにひととおり情報入力させたあとに、signup失敗ですやり直してくださいとか返ってきたらキレそうだ…

signup時はgoogle認証した後に一旦token載せてsignupAPI叩いて、
うまくいったらprofile項目入力してもらってprofileのupdate叩けば良さそうかな？

2020-07-23 03:26 UTC, sana37 commented
@ho2ri2s 
> signup時はgoogle認証した後に一旦token載せてsignupAPI叩いて、
うまくいったらprofile項目入力してもらってprofileのupdate叩けば良さそうかな？

そうしようと思う！
* signupではJWT乗っけるだけ、リクエストbodyはいらない
* profile情報の登録にはprofileのupdateのみを使う

って感じで！

2020-07-25 08:54 UTC, sana37 commented
修正しました！

主な修正点
* user, profile の統一および整理
* album, wish_listのメンバーの追加方法について、参加API（招待リンク）を使用
* JWTを使った認証情報を追加
* タイムラインAPIにページングを追加
* パラメータにフォーマット情報を追加
* multipart/form-dataを使ったスキーマ定義を忘れていたのでそこの修正

2020-07-25 12:23 UTC, Takumaron commented
これ議論が必要かもしれないんだけど、「ユーザのプロフィール取得API」でパスパラメータが{user_id}になっているけど、個人的には{user_name}の方が良いのではないかと考えている。
せっかくuser_nameという情報を持たせて、ユーザを一意に識別できるようにするのであれば、それを使いたい。

2020-07-25 12:25 UTC, Takumaron commented
「プロフィール情報の更新API」についてだけど、 `/users`では更新するユーザを特定できないので、「ユーザのプロフィール取得API」と同様にパスパラメータの指定が必要そう。

2020-07-25 12:55 UTC, TakumaKurosawa requested changes
一旦スプリント1に関しては、これだけ変更してもらえればOKそう！

2020-07-25 12:55 UTC, Takumaron commented on docs/reference/wantum.v1.yaml
> +      summary: ユーザのプロフィール取得
これ議論が必要かもしれないんだけど、「ユーザのプロフィール取得API」でパスパラメータが{user_id}になっているけど、個人的には{user_name}の方が良いのではないかと考えている。
せっかくuser_nameという情報を持たせて、ユーザを一意に識別できるようにするのであれば、それを使いたい。

@sana37
@akubi0w1

2020-07-25 12:55 UTC, Takumaron commented on docs/reference/wantum.v1.yaml
> +      summary: プロフィール情報の更新
「プロフィール情報の更新API」についてだけど、 /usersでは更新するユーザを特定できないので、「ユーザのプロフィール取得API」と同様にパスパラメータの指定が必要そう。

2020-07-25 12:55 UTC, Takumaron commented on docs/reference/wantum.v1.yaml
> +      summary: カテゴリー新規作成
`/categories`ではどのリストのカテゴリーを作成するかが分からないので、下記のような形でRESTに準拠して欲しい。

`/wishlists/{wishlist_id}/categories`

その他の親子関係についてもおんなじように、エンドポイントから一目でどのリソースにリクエストしているかわかるようにして欲しい！

2020-07-26 01:42 UTC, sana37 commented on docs/reference/wantum.v1.yaml
> +      summary: プロフィール情報の更新
これは、JWTからユーザ特定できるからユーザIDはいらないと思った。
自分のプロフィール以外を更新することはありえないからJWTだけでいいかな、って感じ
今、思ったんだけど、`/users`だとパスパラメータがないと違和感を感じるから、
`/profile`にした方がいいかもしれない…（こっちの方が”自分の”プロフィールをいじってる感が出る気がする）

2020-07-26 01:49 UTC, sana37 commented on docs/reference/wantum.v1.yaml
> +      summary: ユーザのプロフィール取得
いいかも！
見栄えもいいし、id直接さらさなくて済むならそのほうがいいね！

2020-07-26 01:58 UTC, sana37 commented on docs/reference/wantum.v1.yaml
> +      summary: カテゴリー新規作成
なるほど！
だとしたら、
* categories
* wish_cards
* memories

これら３つのPOSTだけ親子関係がわかるように直す感じでいいかな？

GET, PUT, DELETEに関しては、親の情報はいらないよね？

2020-07-26 12:45 UTC, Takumaron commented on docs/reference/wantum.v1.yaml
> +      summary: プロフィール情報の更新
確かに！
`/users/profile`とかどうだい？？

2020-07-26 12:46 UTC, Takumaron commented on docs/reference/wantum.v1.yaml
> +      summary: カテゴリー新規作成
いや、基本的には全てのメソッドに対して必要かな。
強いていうなら、GETだけはWish＿list取得時に子供も全て取得するはずやから、いらないかなー

2020-07-27 01:12 UTC, akubi0w1 commented on docs/reference/wantum.v1.yaml
> +      summary: ユーザのプロフィール取得
それでも良さそう！だし見栄え良さそう！
ただここの辺、クライアントとも確認とった方がいいかも。
user_id(int), auth_id(firebase id), user_nameって色々あるから、このへんの認識含めて話すのが良いのでは？と思った！

2020-07-27 01:14 UTC, akubi0w1 commented on docs/reference/wantum.v1.yaml
> +      summary: プロフィール情報の更新
これは確かに`id`含めない方がセキュリティ堅い！
`/users/self`とかで対応する例も見たことあるけど、`/users/profile`の方がよさげやね。

2020-07-27 01:22 UTC, akubi0w1 commented on docs/reference/wantum.v1.yaml
> +          description: Internal Server Error
これ最初のレビューで気付けって話でほんと申し訳ないんだが、
401, 403...とかのエラーも、jsonでレスポンスが行くんよね。jsonの構造は、おそらく全エラーで共通なんだけど、一応明記した方がいいのかなーとおもった。
エラー毎に、`content`ディレクティブがある、もしくは、modelを書いておく方が良いかも。

2020-07-27 06:18 UTC, sana37 commented on docs/reference/wantum.v1.yaml
> +      summary: カテゴリー新規作成
URL長くなっちゃうのがいやで避けてたんだけど、わかりやすさの方が大事だし仕方ないか〜
参考にgithubのAPIを見てきたんだけど、やっぱり親子関係がわかるように作られてたわ。
了解！他のメソッドも直します！

2020-07-27 06:19 UTC, sana37 commented on docs/reference/wantum.v1.yaml
> +      summary: プロフィール情報の更新
`/users/profile`でいきます！

2020-07-27 06:26 UTC, sana37 commented on docs/reference/wantum.v1.yaml
> +          description: Internal Server Error
こうやって見返すと、自分がどんなにサボってたかが分かってくるな…？？
エラーのjsonも必要だわ…！

2020-07-27 06:28 UTC, Takumaron commented on docs/reference/wantum.v1.yaml
> +      summary: ユーザのプロフィール取得
@akubi0w1 
確かにそれは絶対言えてるな！
スプリントの振り返りMTGのタイミングで進捗報告で出来上がったDB設計書を見せながら共有・議論できるようにしておこう！👍

2020-07-27 06:29 UTC, Takumaron commented on docs/reference/wantum.v1.yaml
> +      summary: カテゴリー新規作成
オネシャス！

2020-07-27 06:32 UTC, Takumaron commented on docs/reference/wantum.v1.yaml
> +          description: Internal Server Error
@akubi0w1 気づいてくれてサンキュー👍

@sana37 
参考までに、JSONの中身としては、日本語のエラー文＋英語のエラー文という感じになります！イメージとしてはこんな感じ↓

``` json
{
  "error_jp": "リクエストされたリソースはすでに破棄された可能性があります。",
  "error_en": "whish_list is not found."
}
```

2020-07-27 10:21 UTC, sana37 commented
再度修正しました！
* 更新系はPUT ではなく PATCH
* pick専用APIの削除
* ユーザのプロフィール取得APIにuser_nameを使用
* リソースの親子関係がわかるようにAPIのURLを修正
* エラーレスポンスのjsonを追加

2020-07-27 12:17 UTC, akubi0w1 commented
自分、土下座いいですか？
memoriesのUPDATEってないのかなと今更思ってしまった...
これって普通に仕様上ない感じか...？
まじで今更気づいて土下座します...

その他はそこまで気にならなかったです！

これは普通に興味なのだが、更新時のmethodやけど、PUT -> PATCHにした理由とかって何かある感じですか？
更新 = PUTかなーっていうイメージだったので、気になってしまった。。。！
githubのAPI参考にしてそうだったので、自分もちょっとのぞいて考えてみたんだが、部分更新がPATCH、完全な置きかわりがPUTだったんで、確かにPATCHのほうが自然かなあーと思った！今回リクエストのbodyがほぼoptionなので！

- [githubAPI 動詞の説明のとこ](https://developer.github.com/v3/#http-verbs)

2020-07-29 03:08 UTC, sana37 commented
@akubi0w1 
お顔を上げてくだせえ、あくび様！！
memoriesの更新・削除はロードマップ１にはなかったから、必要になってからでいいかな、と勝手に判断しやした！

PATCHについてはそのとおりです！
githubのAPI見てて気になったから調べてみたら
* PUTは元リソースがあるなしにかかわらず上書き
* PATCHは部分更新

ってのを見つけて修正した！

参考記事↓
> https://qiita.com/suin/items/d17bdfc8dba086d36115

2020-07-29 06:56 UTC, akubi0w1 approved these changes
@sana37 
なるほどー！確かにスコープ入ってないからなくて良いかもw
ざーと見た感じLGTMです！！！

2020-07-30 12:47 UTC, TakumaKurosawa approved these changes
レスポンスに関する所以外は一旦OKなので、修正したらマージしちゃってください！
Stoplightで余分な情報とか載っちゃっていると思うからその辺り消せそうなら消してもらえるとありがたい！

2020-07-30 12:47 UTC, Takumaron commented on docs/reference/wantum.v1.yaml
> +                $ref: ../models/categories.v1.yaml
ここだけじゃないんだけど、レスポンスボディが空の場合は204(No content)にしてほしいかな！

2020-08-01 06:51 UTC, sana37 commented on docs/reference/wantum.v1.yaml
> +                $ref: ../models/categories.v1.yaml
リクエスト成功は全部200に統一した方が、間違いが少なくていいと思ってるんだよね〜
どう思う？
やっぱレスポンスのあるなしをわかりやすくするのって大事？

2020-08-01 07:58 UTC, akubi0w1 commented on docs/reference/wantum.v1.yaml
> +                $ref: ../models/categories.v1.yaml
返すコンテンツが何もないなら、204の方が「なにもないことが正常である」ことを明示できるから、良いのかなと思っている！
クライアントでどういう処理するかによっては、200に揃えた方が良いことがあるのかもしれないけどな、、、。

2020-08-01 08:14 UTC, sana37 commented on docs/reference/wantum.v1.yaml
> +                $ref: ../models/categories.v1.yaml
そうか〜。
おけ、204になおすわ！

2020-08-01 08:28 UTC, merged