docker-composeを用いた環境構築
TechCafeFreedom/Wantum-server pull request #17
Opened 2020-07-31 08:10 UTC by akubi0w1

## Issue
close #8  

## 概要
docker-composeを用いた環境の構築。golangとmysqlの環境を作成した。

## 変更内容
- docker-compose / Dockerfile / DB初期化用スクリプトの作成
- goに関して、ホットリロードに対応
- DB周りのファイルを移動
- Makefile / README.mdの編集

## 動作確認方法
- `make env-up`にて起動後、`make env-api-watch` でログを監視しつつ、テスト用のgoファイルを動かしてホットリロードの確認
- `make env-stop`にて、コンテナの停止
- `make env-start`にて、コンテナの起動
- `make env-down`にて、コンテナ、コンテナイメージの削除
- `make env-db-init`にて、DBの初期化
- `make env-db-dump`にて、mysqldumpの動作を確認

## 補足事項
README、Makefile、.gitignoreに関して、それぞれくろちゃんのファイルに書き足すイメージで書きました。

2020-08-01 00:17 UTC, TakumaKurosawa approved these changes
コメントしました！
バイトでこの後レビューできないと思うから、Approve出しちゃいますが、コメントしたあたりは修正してもらえるとありがたいです！

2020-08-01 00:17 UTC, Takumaron commented on docker/go/Dockerfile
> +    && go build -o ./binary/app ./cmd
マルチステージビルドにした方がDockerのキャッシュを効かせられるのと実行イメージが軽量で済むので、対応をお願いします！
イメージとしてはこんな感じ↓

``` Dockerfile
FROM golang:alpine3.11 as builder
ADD . /go/src/github.com/geospa
WORKDIR /go/src/github.com/geospa

ENV GO111MODULE=on

RUN apk update && \
    apk add git && \
    GOOS=linux GOARCH=amd64 go build main.go wire_gen.go

FROM alpine:3.9
EXPOSE 8080

WORKDIR /app
COPY --from=builder /go/src/github.com/geospa /app

ENTRYPOINT ["./main"]
```

2020-08-01 00:17 UTC, Takumaron commented on docker-compose.yml
> +    command: realize start --run
realize使っているということはこれはあくまで開発環境として使うコンテナという認識で合っている？

2020-08-01 00:17 UTC, Takumaron commented on Makefile
> +	docker-compose start
「開発環境の起動」と「全コンテナを起動」の違いがよくわからないんだけど、どう違うのかな？

2020-08-01 00:17 UTC, Takumaron commented on Makefile
> +	docker-compose down --rmi local
downしたらイメージも消えてくれるの助かる。

2020-08-01 00:17 UTC, Takumaron commented on docker-compose.yml
> +      - .:/go/src/wantum
.dockerignoreを書いて、ビルドに不要なファイルはコンテナイメージに含めないようにしてほしい！

2020-08-01 01:20 UTC, akubi0w1 commented on docker-compose.yml
> +    command: realize start --run
そうやね！
とどねのインフラ環境がdocker-compose使わずに行ったから、インフラでは使わないイメージを持っておった。。。

2020-08-01 01:33 UTC, akubi0w1 commented on Makefile
> +	docker-compose start
コンテナが作成されていない状態では`env-up`、コンテナがある状態(stopしている状態)では`env-start`する、みたいな違いだった！
ただstopした状態でもupで起動だけできるから、startいらんわ...

2020-08-03 05:37 UTC, Takumaron commented on docker-compose.yml
> +    command: realize start --run
OK!

2020-08-03 05:45 UTC, TakumaKurosawa requested changes
再度コメントしました！

2020-08-03 05:45 UTC, Takumaron commented on Makefile
> +	docker-compose exec db /usr/bin/mysqldump -u root -proot wantum > /dev/null > ./db/mysql/dump/mysqldump.sql
ごめん！言い忘れていたんだけど、 `make help`でコマンド一覧を確認できるスクリプトが ＃2つじゃないと検知してくれないから、各コマンドのコメントを #2個にして欲しい！

2020-08-03 05:45 UTC, Takumaron commented on README.md
> +env-db-dump   DBをダンプする。出力先は /db/mysql/dump。ディレクトリは自動で作成されます。
ワンチャンプロダクション用のコマンドを生やす可能性が出てきたときに、 `env-`だと開発環境かプロダクション環境かわかりづらいので、 `dev-`のが良い気がする！

2020-08-03 05:45 UTC, Takumaron commented on docker/go/Dockerfile
> +CMD ["./binary/app"]
docker-composeの方で記述している、 `command: realize start`でコマンドが上書きされてしまっているので、どちらを実行したいかに合わせて、docker-composeでのcommand定義を無くした方が良さそう。

2020-08-03 06:53 UTC, akubi0w1 commented on Makefile
> +	docker-compose exec db /usr/bin/mysqldump -u root -proot wantum > /dev/null > ./db/mysql/dump/mysqldump.sql
そうなんか！！！おけい！修正します！！！

2020-08-03 06:53 UTC, akubi0w1 commented on README.md
> +env-db-dump   DBをダンプする。出力先は /db/mysql/dump。ディレクトリは自動で作成されます。
確かに！意見ありがとう！助かります！！
直しておきますー！

2020-08-03 06:53 UTC, akubi0w1 commented on docker/go/Dockerfile
> +CMD ["./binary/app"]
これなんやけど、docker-composeの方で`build.target`を`build`(golangの環境)にしているから、alpineの方に降りてきてないんよね。作業的に、ホットリロードあった方が開発やりやすいかなと思ったので！
ターゲット絞ってるんだけど、全体をビルドした方が良さげかな。。？

一応、docker-composeの方でcommand定義を無くした時に、マルチステージビルドでも動くのは確認済みです！

2020-08-03 08:25 UTC, sana37 commented on Makefile
> +	docker-compose logs log
凡ミスかな？
log→db

2020-08-03 08:25 UTC, sana37 commented on docker/go/Dockerfile
> +    && go get -v ./... \
ただの質問なんだけど、ここって何やってるの？
ググろうにも`./...`で検索しづらい、、

2020-08-03 08:25 UTC, sana37 commented on docker-compose.yml
> +      - .:/go/src/wantum
ここって、
`.:/wantum`
じゃない？
firebaseで使うjsonとかにアクセスするためのボリュームだよね

2020-08-03 08:25 UTC, sana37 commented on Makefile
> +	docker-compose exec db /usr/bin/mysqldump -u root -proot wantum > /dev/null > ./db/mysql/dump/mysqldump.sql
ここで`/dev/null`に捨ててるのってなんで？

2020-08-03 09:05 UTC, akubi0w1 commented on Makefile
> +	docker-compose logs log
めっちゃ恥ず、、、！
修正します！指摘ありがとう！

2020-08-03 09:05 UTC, akubi0w1 commented on docker/go/Dockerfile
> +    && go get -v ./... \
アプリケーションが依存しているパッケージを取得してます！
`./...`って指定してあげると、カレントディレクトリを起点にして再帰的にパッケージの探索を始めてくれるらしい！
https://stackoverflow.com/questions/28166249/how-to-list-installed-go-packages

この指定方法、なんとなく使ってたから勉強になった...！

2020-08-03 09:06 UTC, akubi0w1 commented on docker-compose.yml
> +      - .:/go/src/wantum
ここは、ローカル環境をコンテナに同期させてあげるボリュームなので、これであってると思う！
ホットリロードを実現するために同期させてます！

2020-08-03 09:06 UTC, akubi0w1 commented on Makefile
> +	docker-compose exec db /usr/bin/mysqldump -u root -proot wantum > /dev/null > ./db/mysql/dump/mysqldump.sql
コンテナ内にダンプファイルを作らないためですー！
ダンプファイルはローカルに吐き出すので、コンテナ内に残す必要ないかなと。

2020-08-03 09:11 UTC, akubi0w1 commented on Makefile
> +	docker-compose exec db /usr/bin/mysqldump -u root -proot wantum > /dev/null > ./db/mysql/dump/mysqldump.sql
`mysqldump -u root -proot wantum > ./db/mysql/dump/mysqldump.sql`
これでも大丈夫やな...？

2020-08-03 13:55 UTC, sana37 commented on docker-compose.yml
> +      - .:/go/src/wantum
ホットリロード用か！

あ、俺が思ったのは、ビルド用コンテナでは`/go/src/wantum`上で作業してるけど、バイナリ置く用コンテナでは`/wantum`上で作業してるから、ボリューム通すべきはこっちかなって

2020-08-03 14:05 UTC, sana37 commented on Makefile
> +	docker-compose exec db /usr/bin/mysqldump -u root -proot wantum > /dev/null > ./db/mysql/dump/mysqldump.sql
ためしに
```
echo aiueo > a.txt > b.txt
```
で実行してみたら`b.txt`だけに書き込まれてた…

`> /dev/null`はいらないかなあ？

2020-08-03 14:07 UTC, sana37 commented on docker/go/Dockerfile
> +    && go get -v ./... \
たすかる！
こういうやり方があるのね！

2020-08-04 00:45 UTC, akubi0w1 commented on docker-compose.yml
> +      - .:/go/src/wantum
バイナリ置くコンテナまでビルドするときは、volume通さんかな。
goのdockerfileで、コードをgoコンテナにコピー -> goコンテナでバイナリの作成 -> alpineにバイナリだけコピーって流れで、volumeする必要がないんよね。！

2020-08-04 00:46 UTC, akubi0w1 commented on Makefile
> +	docker-compose exec db /usr/bin/mysqldump -u root -proot wantum > /dev/null > ./db/mysql/dump/mysqldump.sql
それ、、、自分も試したら`/dev/null`いらなかった...！
指摘ありがとう！勉強になった！！

2020-08-04 14:28 UTC, sana37 commented on docker-compose.yml
> +      - .:/go/src/wantum
あ、、、`target:build`ってしてるから`docker-compose up`したときはビルド用コンテナが実行されるのか、、、
毎回alpineの方が実行されるのかと思ってたわ…
失礼しやしたぁ！

2020-08-14 13:42 UTC, Takumaron commented on docker/go/Dockerfile
> +    && go get -v ./... \
俺も勉強になった！

2020-08-14 13:46 UTC, Takumaron commented on docker/go/Dockerfile
> +CMD ["./binary/app"]
そういうことであればOKです！

2020-08-14 13:47 UTC, TakumaKurosawa approved these changes
修正してくれたやつ見る感じ良さそうなので、マージしちゃいます！

2020-08-14 13:47 UTC, merged