コードの骨組み作成＆Google認証でユーザ登録/ログインができるようにする
TechCafeFreedom/Wantum-server pull request #7
Opened 2020-07-05 14:29 UTC by Takumaron

## Issue

close #4 

## 概要

## タスク整理

- [ ] hoge
- [ ] fuga

## 変更内容

## 動作確認方法

## 補足事項

2020-07-24 14:22 UTC, TakumaKurosawa reviewed
補足情報についてはコメント残しました。

2020-07-24 14:22 UTC, Takumaron commented on db/mysql/ddl/ddl.sql
> +CREATE INDEX idx_users ON wantum.users (uid);
これはあくびの #15 がマージされたタイミングで書き換えが必要。

2020-07-24 14:22 UTC, Takumaron commented on pkg/api/middleware/firebase.go
> +			}
この辺のロギング処理については、ロギングしているところ全てがおんなじコードになっており、DRYの原則から逸脱している。
何か良い方法を思いついた人は教えて欲しいです。

2020-07-24 14:22 UTC, Takumaron commented on pkg/api/response/http.go
> +)
middlewareパッケージと循環参照エラーを引き起こしてしまうため、渋々こっちにも定義している。

2020-07-31 04:49 UTC, akubi0w1 requested changes
遅くなって申し訳ない！！！
ざーっと見てみました！普通にザルって見逃してる場所とかあると思う、、、

いくつか気になったこととかがあるので、こっちで！

## リクエストのバリデーション
CreateUserのRequestBodyのバリデーションってどこでやるのかな、と。おそらくhandlerでやることになるのかな...？

## GCP
プロジェクトとか作った方がいい感じよな。。。
この辺どうしようか決めておきたいね、、、！とどねのときの基盤を再現する感じでいくなら、やってみます、、、！

## 500系エラーの文言
`errors.New`で作成する方にはエラー内容を詳しく書く、クライアントに通知する文言は「サーバでエラーが発生しました」とか「保存に失敗しました」くらいシンプルな方が自然かも？と思いました！
アプリの利用者にサーバのエラー内容を細かく通知する意味ってあまりないかな、と感じたので。

## エラーハンドリングとロギングについて
全体をばーっとみたんだけど、基準というか、法則がいまいち掴めなかったので、質問を兼ねて。。。

エラーハンドリングについて、以下の点が明確になっていれば教えていただきたいです。。。！
- ハンドリング時、`Stack` or `Wrap` or `Newf`のどれを使うか
- ログを吐くタイミング(`tlog.GetAppLogger().Error()`をやるタイミング)

## クライアントアプリについて
vueがわからんっていうのと、おそらくログインデバッグ用だろうなーってことで、コードレビューってほどちゃんとコードをみてないです。。。
手動で動かした感じ、問題なさそうだったので、、、(ㅅ ;´꒳`;)

2020-07-31 04:49 UTC, akubi0w1 commented on .env_example
> +MYSQL_DATABASE=wantum
ここに、`MYSQL_PORT`があるとありがたいなあ...と思った...( ˘ω˘ )

2020-07-31 04:49 UTC, akubi0w1 commented on .github/ci.yml
> +                run: go test -v ./...
slackへの通知は飛ばさない感じ？

2020-07-31 04:49 UTC, akubi0w1 commented on cmd/main.go
> +	r := mux.NewRouter()
`NewRouter`だけでCORS対応になってるっていうのは怪しいかも。
いくつかレスポンスヘッダ(`Access-Control-Allow-Origin: http://example.com`とか)つけなければいけなかったはずなのと、OPTIONSメソッドのリクエストが405してしまうと思う。

Gorillaでmethod指定すると、例えばプリフライトリクエストで`/users`にOPTIONメソッドが飛んでくると405で弾かれてしまうんよね。なので、OPTIONSを受けるエンドポイントを作るか、`/users`のMethodsに`"OPTIONS"`を追加する必要があると思う！
後者で実装した場合、`OPTIONS`メソッドのリクエストだった時にAPIの本処理(必要な値を生成したり、DBに突っ込んだり)は行わないので、事前にレスポンスせねばならないので注意です！

2020-07-31 04:49 UTC, akubi0w1 commented on Makefile
> +	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
ヘルプあるのめっちゃ助かります！ありがとうー！！！

2020-07-31 04:49 UTC, akubi0w1 commented on cmd/main.go
> +	log.Fatal(srv.ListenAndServe())
ここのログってtlogで出さない感じ？
ログは出来るだけフォーマット揃えた方が良いかなと思った。。。

2020-07-31 04:49 UTC, akubi0w1 commented on db/mysql/connect_db.go
> +	dataSource := fmt.Sprintf("%s:%s@tcp(%s:3306)/%s?parseTime=true", dbuser, dbpassword, dbhost, dbname)
個人的に嬉しいっていう意見ですが、、、`PORT`もenvとかで設定できるとありがたい...！

2020-07-31 04:49 UTC, akubi0w1 commented on db/mysql/ddl/ddl.sql
> +CREATE INDEX idx_users ON wantum.users (uid);
めっちゃごめんなんだが...
ここで書いてる`uid`ってカラムが、私のDDLだと`auth_id`って名前なんよね...
このDDLと私のDDLで結構相違点があるから、repositoryとかresponseBodyとかに影響行っちゃうかもです...(ㅅ ;´x`;)

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/handler/user/server.go
> +		response.Error(w, r, werrors.Stack(err))
この辺、bodyを空にしてリクエストすると処理されるんだが、`werrors.Stack()`を通った時にログが吐かれなかったんよね。エラーのコンバートに失敗してたので、`werrors.Stack(werrors.Wrapf(err, 400, "jsonが空", "empty json"))`みたいにした方がいいかも。
ログが抜けちゃうのはちょっとやべえので、修正した方がいいとおもう！

以降にもおそらくこういう部分があって、handlerで発生するエラーで生のerrorを`Stack`に送ってる部分全部で起きると思う！

`werrors.Stack`の方はそっちに意見を書くので、そちらを参考にしてくださいー！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/handler/user/server.go
> +	w.WriteHeader(http.StatusNoContent)
ここで`NoContent`にしたのって理由あったりする？
作成されたuserをresponseBodyにつけるって感じかなと思っていたからめっちゃびっくりした、、、！
雛形だから仮置きで`NoContent`なのかなーって思ったりなどした！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/middleware/firebase.go
> +			}
ここの部分めっちゃ思ってた！w

当時のメモコピペで失礼します！

`pkg/api/response/http.go`とか`pkg/infrastructure/mysql/user/repository.go`まわりで何回か見かけたんだけど、以下の部分を関数で切り出せるとかっこいい気がする。logの文面変えるってなったら途方もないので。

`PrintLogWithUID(r http.Request, err error)`みたいな関数を、tlogパッケージに公開で置いてしまうとかかなあ。appLoggerが型でなかったから、メソッドみたいにして生やせないんよな...。配置場所についてはめっちゃ迷う。
関数で切り出したら、多分`runtime.Caller(1)`になるのかな...
最後のエラーレスポンスは除外しないといけないか

```
func PrintLogWithUID(r http.Request, err error) {
        // どこで起きたエラーかを特定するための情報を取得
	pt, file, line, _ := runtime.Caller(0) // Caller(1)か？
	funcName := runtime.FuncForPC(pt).Name()

	// エラーログ出力
	uid, ok := r.Context().Value(AuthCtxKey).(string)
	if !ok {
		tlog.GetAppLogger().Error(fmt.Sprintf("<[Unknown]Error:%+v, File: %s:%d, Function: %s>", err, file, line, funcName))
	} else {
		tlog.GetAppLogger().Error(fmt.Sprintf("<[%s]Error:%+v, File: %s:%d, Function: %s>", uid, err, file, line, funcName))
	}
}
```

呼ぶ時は、`tlog.PrintLogWithUID()`で呼べると思う

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/middleware/firebase.go
> +		log.Panic(fmt.Errorf("error initializing firebase app: %v", err))
この辺も、ログやエラーは自前のもの使った方がいいかも。

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/request/reqbody/user.go
> +	Thumbnail string `json:"thumbnail"`
仕様に合わせてリクエストの修正お願いします...！(ㅅ ;´x`;)

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/response/http.go
> +)
この辺りの定数みたいなところ、`/pkg/util/constants.go`みたいなファイル作ってまとめたらどうかなーって思ったりした！
定数に変更あった時も一箇所に集中してるから管理しやすいかなあーと。

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/response/http.go
> +		_, _ = w.Write(data)
戻り値の意味がだいぶないので、`w.Write(data)`で良いと思う！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/response/http.go
> +	_, _ = w.Write(data)
ここも、`w.Write(data)`で良いと思う！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/response/http.go
> +	_, _ = w.Write(data)
ここも、`w.Write(data)`で良いと思う！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/response/user.go
> +type UserResponse struct {
仕様に合わせて変更が必要かもしれない！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/usecase/user/interactor.go
> +		return werrors.Stack(err)
この辺りのエラー、werrorsでラップしなくていい感じ...？
`Stack()`でコンバートエラーになってしまう気がする。。

あと、もしラップしない、するの明確な基準があれば教えていただけると！助かります！！！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/domain/entity/user.go
> +type User struct {
この辺も仕様に合わせて変更になると思うので、よろしくお願いします...！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/domain/service/user/service.go
> +		return werrors.Stack(err)
ここら辺のエラーについても、werrorでラップしないのか？って思ったりなどした！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/domain/service/user/service.go
> +	GetAll(ctx context.Context, masterTx repository.MasterTx) (entity.UserSlice, error)
`entity.UserSlice`もポインタにできんかったっけ。。。
配列でかくなるから、`*entity.UserSlice`の方がいいかも

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/infrastructure/mysql/user/repository.go
> +			return nil, werrors.Newf(err, http.StatusInternalServerError, "ユーザは1人も登録されていません。", "User doesn't exists.")
ここの部分、エラーにするかは迷う。。。
ユーザが誰もいないこと自体はエラーではない気がするんよな...。誰もいないとか、何もないっていうのは今回の場合、そういう状態もあり得るので。。。

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/werrors/werrors.go
> +		}
ここでreturnするんじゃなくて、以下な感じでもいいかなーって思ったりなどした。

```
errorCode = http.StatusInternalServerError
errorMessageJP = "サーバでエラーが発生しました"
errorMessageEN = "Error occured on server"
```

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/middleware/firebase.go
> +			response.Error(w, r, werrors.Newf(err, http.StatusUnauthorized, "トークンが無効です", "invalid token error."))
認証トークンが空の時はログ吐いているけど、無効なトークンの時にログ吐いてない、ってなってるので修正した方が良いかも！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/handler/user/server.go
> +	response.JSON(w, r, user)
このレスポンスのuser, domainの`entity.User`では...？
レスポンスにconvertできてないかも！

2020-07-31 04:49 UTC, akubi0w1 commented on pkg/api/handler/user/server.go
> +	response.JSON(w, r, users)
多分ここも`entity.UserSlice`になってると思う！
responseのconvertお願いします！

2020-08-02 07:59 UTC, sana37 commented on pkg/infrastructure/mysql/user/repository.go
> +type userModel struct {
個人的な意見なんだけど、ここの`userModel`はいらないんじゃないかな？
直接`Row`から`entity.User`に値を渡しちゃう感じの方がいいかな、と。

そして、Entityにはテーブル定義と同じパラメータが入ると思ってるから、
`entity.User`にはcreatedAtとかの全部のパラメータを入れたい。

あとは、handlerあたりでentityからResponseへの変換をするとか。

2020-08-02 07:59 UTC, sana37 commented on pkg/api/handler/user/server.go
> +	}
この、BodyからBufferにデータ流す部分の処理って、これからいろんなAPIで使うことになりそうだから、
`pkg/api/request`のどこかしらに関数として切り出したいかも

2020-08-02 07:59 UTC, sana37 commented on pkg/api/handler/user/server.go
> +	}
エラーレスポンスを返す部分の記述なんだけど、errMessageは`handler`内じゃなくて`werros`内に全部まとめちゃうってのはどうかな？
例えば、`pkg/werrors/response.go`とかに定数として

```
AuthFail := WantumError{
  ErrorCode: "auth.failed",
  ErrorMessageJP: "ほげ",
  ErrorMessageEN: "hoge",
}
UserNotFound := WantumError{
  ErrorCode: "user.notfound",
  ErrorMessageJP: "ほげ",
  ErrorMessageEN: "hoge",
}
```
みたいな感じで！

あと、勝手に`WantumError`の構造を勝手に変えて書いちゃってるんだけど、これは、
* `StatusCode`よりも粒度が細かくて、なおかつエラー箇所を特定するために便利なものとして`ErrorCode`が欲しい
* レスポンスとして返すようのデータとログに書き出すようのデータは別の構造体に分けたほうがいい

って思ったから！

2020-08-02 07:59 UTC, sana37 commented on pkg/infrastructure/mysql/mysql_tx_manager.go
> +}
せっかく`sql.DB`とか`sql.Tx`を隠蔽してるのに、ここで取り出せるようにしちゃってるのってどうなんだろう？
`ExtractTx()`の使用は`infrastructure`内に抑えられてるから、全然これでいいとは思ってるんだけど！

この質問は、レイヤードアーキテクチャの勉強としての意味が強いから、治してほしいというよりは意見が聞きたいって感じ！

2020-08-03 05:52 UTC, Takumaron commented on db/mysql/ddl/ddl.sql
> +CREATE INDEX idx_users ON wantum.users (uid);
@akubi0w1 
それを想定内で実装していたので大丈夫！

2020-08-03 05:53 UTC, Takumaron commented on pkg/api/middleware/firebase.go
> +			}
そうやね。やっぱ素直に tlogパッケージのメンバ関数にした方が良いのかなー。
ちょっとやってみます。

2020-08-03 05:54 UTC, Takumaron commented on pkg/api/response/http.go
> +)
@akubi0w1 それな！

2020-08-03 05:58 UTC, Takumaron commented on pkg/api/handler/user/server.go
> +	w.WriteHeader(http.StatusNoContent)
@akubi0w1 
さーせん！これは完全に俺の怠慢でしたw
どうせ返すオブジェクト変わるしそのときでいいかー的なw

2020-08-03 05:59 UTC, Takumaron commented on pkg/api/response/http.go
> +		_, _ = w.Write(data)
なんか、golangci-lintのWarningが出るんよねー。。。
まぁ、Warningはいいかーw

2020-08-03 06:01 UTC, Takumaron commented on pkg/domain/service/user/service.go
> +	GetAll(ctx context.Context, masterTx repository.MasterTx) (entity.UserSlice, error)
これはGolangの仕様の話になるんだけど、GoのSliceってそもそも実態としてはポインタなんよ！
これ内定者バイト中に俺も聞いてヘェ〜なるほどな！ってなったところなんよね！

2020-08-03 06:03 UTC, Takumaron commented on pkg/infrastructure/mysql/user/repository.go
> +			return nil, werrors.Newf(err, http.StatusInternalServerError, "ユーザは1人も登録されていません。", "User doesn't exists.")
確かに・・・・
このエラー督促何の意味がある？？？w

2020-08-03 07:25 UTC, akubi0w1 commented on pkg/api/handler/user/server.go
> +	}
`ErrorCode`の部分なんだけど、あくまでwantumErrorは、response用(クライアントに見せる用)かつHTTPResponseのステータスコードの設定に使っているから、このままの方がいいかも。
エラー個所の特定についてなんやけど、スタックトレースとか、callerがログに出るから追跡はできると思う！

`ErrorCode`の案はめっちゃ参考になるわ、、、！

2020-08-03 08:42 UTC, sana37 commented on pkg/api/handler/user/server.go
> +	}
@akubi0w1 
もちろんステータスコードの情報も必要なんだけど、別の構造体に分けられないかな？
エラーレスポンスのjsonと全く同じ形の構造体があるとわかりやすいと思って。

例えば、`WantumError`にはステータスコードとかログの情報を入れて、
別の構造体`ErrorResponse`には`ErrorCode`とかエラーメッセージが入ってる感じ。

response.Error()には２種類の構造体を渡す、もしくは、２種類の構造体を生成するのに十分なキーになる値だけを渡す、とか。

2020-08-15 02:08 UTC, Takumaron commented on .github/ci.yml
> +                run: go test -v ./...
追加しました！

2020-08-15 02:40 UTC, Takumaron commented on cmd/main.go
> +	r := mux.NewRouter()
CORS対応しようと思ってコメント残しておいてよかった！
完全に抜けてましたw

2020-08-15 02:54 UTC, Takumaron commented on cmd/main.go
> +	log.Fatal(srv.ListenAndServe())
あざす！ここ以外のところも含めて、標準パッケージの`log`を使っているところは`tlog`に置き換えました！

2020-08-15 05:15 UTC, Takumaron commented on pkg/api/middleware/firebase.go
> +			}
tlogパッケージのメンバ関数として切り出してみました！

2020-08-15 08:28 UTC, Takumaron commented on pkg/api/handler/user/server.go
> +	w.WriteHeader(http.StatusNoContent)
作成したユーザ情報を返すようにしました。

2020-08-15 08:28 UTC, Takumaron commented on pkg/api/handler/user/server.go
> +	response.JSON(w, r, user)
確かにコンバート処理を忘れていた！

2020-08-15 09:17 UTC, Takumaron commented on pkg/api/handler/user/server.go
> +		response.Error(w, r, werrors.Stack(err))
確かに独自エラーじゃない生のエラーなのにWrapせずにStackしたらそりゃエラーになるわw
気付いてくれてありがとう！

2020-08-15 09:21 UTC, Takumaron commented on pkg/api/usecase/user/interactor.go
> +		return werrors.Stack(err)
ここは、Usecase層にエラーが伝搬してきている時点でどこかで`Newf`か`Wrapf`して独自エラーに変換されているはずなので`Stack`で良いという判断です！

WrapするのかStackするのかの基準は、独自エラーに変換済みのエラーか生のエラーかで判断してもらえると良いです。
例えば、DBアクセス時に発生したエラーなどはあくまでsqlパッケージの内部で生成されたエラーのはずなので、こちらでハンドリングした時にはまだ独自エラーへの変換はできていません！なので、Wrapfなどでラップしてあげる必要があります。

2020-08-15 09:34 UTC, Takumaron commented on pkg/tlog/logger.go
> +}
WithCtxとWithAuthIDがあるのは、層によってコンテキストを持っていたり、コンテキストは持っていないけど、取り出したAuthIDを持っていたりするため.

2020-08-15 09:45 UTC, Takumaron commented on pkg/infrastructure/mysql/user/repository.go
> +type userModel struct {
DBのモデル定義とドメイン層のエンティティーは別の概念として定義したいんよね。
ここまでの例だと特に必要性が感じられないかもしれないんだけど、
例えば、
モデル定義（DBのテーブル定義）的にはUser構造体の中にProfile構造体があるように表現するけど、ドメインから触れるエンティティ定義では、Profileという構造体の中身もUser構造体のプロパティにしたいとかっていうことが出てくる可能性があるので。
DBのモデル定義とEntityを同一の物にしてしまうと、せっかくORMを使わずにモデルとドメインオブジェクトを切り離したのに結局意味ないねって話になってしまうと思う！

2020-08-15 09:47 UTC, Takumaron commented on pkg/api/handler/user/server.go
> +	}
確かに！

2020-08-16 01:56 UTC, Takumaron commented on pkg/infrastructure/mysql/mysql_tx_manager.go
> +}
pkg/infrastructure/mysql/mysql_tx_manager.goでやっていることとして、 `sql.DB`とか`sql.Tx`の隠蔽という認識は少し違っていて、pkg/api/usecaseからトランザクションをまとめられるようにするために作っているマネージャーなんよね。

この独自パッケージでトランザクションを制御していることで、Usecase単位でトランザクションを管理できるから使っているという感じ。

2020-08-16 06:49 UTC, Takumaron commented on pkg/api/handler/user/server.go
> +	}
今回の対応では、
`werrorsパッケージにconstants（定数）として、汎用的なエラーメッセージは定義`
のみ対応。
エラーをよりわかりやすくするための、ErrorCodeの定義は必要になった時にやるということになった。

2020-08-16 06:52 UTC, Takumaron commented on pkg/api/usecase/user/interactor.go
> +	})
@sana37 
こんな感じで、UseCase層からトランザクションを制御したいから、`masterTxManager`っていうパッケージを独自で定義しています！

2020-08-16 07:01 UTC, TakumaKurosawa reviewed
補足情報コメントしました！

2020-08-16 07:01 UTC, TakumaKurosawa commented on pkg/api/usecase/user/interactor.go
> +	})
@sana37 
こんな感じで、UseCase層からトランザクションを制御したいから、`masterTxManager`っていうパッケージを独自で定義しています！

2020-08-16 07:01 UTC, Takumaron commented on pkg/infrastructure/mysql/user/repository.go
> +	)
@sana37 
@akubi0w1 

標準パッケージでJOIN句書こうとしたらめちゃくちゃだるいんやな・・・
特に、 `SELECT *`句が使えないのかなりだるいわ泣
この辺りちゃんと開発メンバーで共有しとかないといけないところなので、これから開発・レビューの時気をつけてください！
もしくはJOIN句を使わず、UserとProfileそれぞれ別々で取ってきたものをプログラム側で結合させるか？？

2020-08-16 14:50 UTC, akubi0w1 reviewed
ざーっと見ましたー！いくつか気になった点があったので、参考程度に見てくれると幸いです！

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/constants/constants.go
> +)
db_connectionとかで使うデフォルトの値(HOST, PORTなど...)もこっちで管理でもいいかなあーって思ったりなどしました！
万一、変更するときにどこだっけ、ってなるの防止で。

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/domain/service/user/service.go
> +	GetAll(ctx context.Context, masterTx repository.MasterTx) (entity.UserSlice, error)
あっそうなんや！初めて知った、、、！
なるほど、、、！

2020-08-16 14:50 UTC, akubi0w1 commented on db/mysql/connect_db.go
> +	tlog.GetAppLogger().Debug("connectDB: local")
好みの問題かもしれないが、DebugよりInfoの方がしっくりくる(個人の所感すぎる)。
DB接続がどこにいってるかってバグ要因の調査というより、通知しておきたい情報っていう感じがするので。
ログレベルにInfoがあればの話です...( ˘ω˘ )

あと、`local`だと情報が死滅しておるので、`user=xxx, target=localhost:3306, db=wantum`みたいな情報があると、DB接続先が間違ってるとか確認しやすそうかな、と思ったりなどした！
おそらくとどねの時に、わたしが`local`って書いてた気がするから、申し訳ない、、、

2020-08-16 14:50 UTC, akubi0w1 commented on db/mysql/connect_db.go
> +	tlog.GetAppLogger().Debug("connectDB: cloudSQL")
ここも、上記の`local`部分と同じく！

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/api/handler/user/server.go
>  func (s *Server) GetUserProfile(w http.ResponseWriter, r *http.Request) {
ここって`UserProfile`より、`User`の方が良かったりしない...？
ニュアンス的にprofileしか取ってこないのかなって思ったけど、user全部持ってきてそう？なので！

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/api/handler/user/server.go
>  	}
authID取り出す部分なんだけど、おそらくミドルウェアを適用する全てのエンドポイントで必要になると思うので、関数にしちゃう方がいいかも。
`pkg/api/wcontext`みたいなパッケージで、`wcontext.go`とかに移植する、みたいな。
気づきが毎回遅くてごめんなさい、、、！

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/api/request/reqbody/user.go
> +	Birth     string
ここって、jsonのアノテーションなしでいけるん...？

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/api/response/user.go
> +type UserProfile struct {
めっちゃ微妙かもしれないが、service、repositoryなどに倣って、`profile.go`に分けてもいいかなと思った。
ただconvertが細分化しちゃうから、厳密にモデルごとで分けるかは好みの問題な気がする、、、。

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/domain/repository/profile/repository.go
> +	InsertProfile(ctx context.Context, masterTx repository.MasterTx, profileEntity *model.ProfileModel) (*model.ProfileModel, error)
select系あった方がよくないか、と思ったー！
userのrepositoryでjoinして取得してるけど、repositoryを厳密に分けるなら、selectも移行させた方がいいかも！変に混ざるとメンテが大変そうなので。。。

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/infrastructure/mysql/user/repository.go
> +	)
いくつかそれ関連でコメントしてるんだけど、UserとProfileで分けた方がいいと思う！
insertで厳密にuserとprofileを分けてるので、`repository : DBのtable = 1 : 1`くらいの感じで。

`SELECT *`って使おうと思えばいけなかったっけ...いけないんだっけ、、、。
あと、`*time.Time`ってこういう形式で取ってこれるんか。。。過去にコケまくった記憶があるので、、、勉強になる。。。

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/infrastructure/mysql/model/user.go
> +	Profile   *ProfileModel
DBのテーブルイメージでモデルを作っておるなら、profileはない方がいいかも？
もしくは、profileIDみたいにする方がいいかも。

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/tlog/logger.go
> +	// どこで起きたエラーかを特定するための情報を取得
ここの関数、uid(authID?)を取り出して`PrintErrorLogWithAuthID`呼ぶって形でも良さそうかなって思った！
uidを取り損ねたら、`PrintErrorLogWithAuthID("")`、取れれば、`PrintErrorLogWithAuthID(uid)`みたいな。ここの変更は好みもあるかもなので、お任せします、、、！

2020-08-16 14:50 UTC, akubi0w1 commented on pkg/werrors/werrors.go
> +		errorMessageEN = "Error occurred in server."
`werrors/constants`で適宜したエラーを使って良さそう？

2020-08-17 07:04 UTC, Takumaron commented on pkg/constants/constants.go
> +)
確かに！まとめました！

2020-08-17 07:57 UTC, Takumaron commented on db/mysql/connect_db.go
> +	tlog.GetAppLogger().Debug("connectDB: local")
こちらの対応と合わせて、ログ出力をコンソールと合わせて `pkg/tlog/log.json` に出力するようにしました！

2020-08-17 08:02 UTC, Takumaron commented on pkg/api/handler/user/server.go
>  func (s *Server) GetUserProfile(w http.ResponseWriter, r *http.Request) {
確かにその通りです！

2020-08-17 08:28 UTC, Takumaron commented on pkg/tlog/logger.go
> +	// どこで起きたエラーかを特定するための情報を取得
そっちで問題なさげだったので、修正しました！

2020-08-17 08:29 UTC, Takumaron commented on pkg/werrors/werrors.go
> +		errorMessageEN = "Error occurred in server."
よくぞ気づいてくれた！！！

2020-08-17 08:32 UTC, Takumaron commented on pkg/api/request/reqbody/user.go
> +	Birth     string
よくぞ気づいてくれた・・・・

2020-08-17 08:52 UTC, Takumaron commented on pkg/api/handler/user/server.go
>  	}
Good提案でした！

2020-08-18 03:34 UTC, Takumaron commented on pkg/infrastructure/mysql/user/repository.go
> +	)
@akubi0w1 
厳密にいうと、 `SELECT *`句自体は使えるんだけどその場合DBのカラムの順番に依存してしまって、ScanするときにそのDBのカラム順と差異があるとエラーになったり、別のカラム情報がアサインされたりしてしまう。

2020-08-18 03:36 UTC, Takumaron commented on pkg/api/response/user.go
> +type UserProfile struct {
@akubi0w1 
提案ありがとう！
個人的にResponseはあくまで内部のモデルとかロジックの影響を受けないようにしたくて、クライアントから見てProfileはUserのプロパティ情報という位置付けになっている以上は現状のような実装にしたいかな。

2020-08-18 03:38 UTC, Takumaron commented on pkg/domain/repository/profile/repository.go
> +	InsertProfile(ctx context.Context, masterTx repository.MasterTx, profileEntity *model.ProfileModel) (*model.ProfileModel, error)
JOIN句を使わないようにする実装で書いてみた！
ただ、JOIN句を使わないとなると自ずとN＋1問題との闘いになってくるので、これからBoardの概念とかでリレーションが出てきた時に意識して実装が必要そう。
下記の記事の中の`mapを使用`を参考にして実装しています。（JOIN句を使うよりは遅いが、N＋1問題は解消できている）
https://qiita.com/muroya2355/items/d4eecbe722a8ddb2568b#map%E3%82%92%E4%BD%BF%E7%94%A8

2020-08-18 03:42 UTC, Takumaron commented on pkg/api/usecase/user/interactor.go
> +		// TODO: 現状の設計だと、UserDataに対してProfile情報が必ず1つだけ存在しないとデータの整合性が保てない設計となっている。
ここチェック！！

2020-08-18 03:54 UTC, Takumaron commented on pkg/tlog/logger.go
> +	config.Encoding = "json"
logファイルに出力しないのであれば、`console`にした方が見やすさは断然変わる。

2020-08-18 04:36 UTC, akubi0w1 commented on pkg/api/response/user.go
> +type UserProfile struct {
なるほど！そういうことなら全然良いと思う！

2020-08-19 06:12 UTC, akubi0w1 approved these changes
良い感じだと思いますー！！
一箇所、userSliceとprofileSliceを結合する部分、ちょっと気になったのだが、いい実装が思い浮かばんので、わたしもちょっと調べつつ考えてみます、、、！

2020-08-19 06:12 UTC, akubi0w1 commented on pkg/infrastructure/mysql/profile/repository.go
> +	var userIDsStr []string
このスライスの確保、`userIDsStr := make([]string, 0, len(userIDs))`の方がパフォーマンス良いかなと！

2020-08-19 06:12 UTC, akubi0w1 commented on pkg/api/usecase/user/interactor.go
> +			userSlice[i].Profile = profileData
rangeのindexとると、userSliceとprofileSliceのデータが同じ順番で並んでいないとバグる気がする。。。
スライスだと順番意識するから、mapとかどうだろうと思ったが、...？下な感じで考えてはみたけど、最後にSliceで返すってなると、map -> sliceでもう一回全件回してappendになりそう。これ重いかな...と思ったり。

```
userIDs := make([]int, 0, len(userSlice))
userMap := make(map[int]UserSlice)
for _, userData := range userSlice {
	userIDs = append(userIDs, userData.ID)
        userMap[userData.ID] = userData
}
...
for _, profileData := range profileSlice {
	userMap[profileData.UserID].Profile = profileData
}
```

2020-08-22 09:13 UTC, sana37 commented on pkg/infrastructure/mysql/user/repository.go
> +type userModel struct {
なるほど了解！

2020-08-23 10:19 UTC, sana37 commented on pkg/api/usecase/user/interactor.go
> +			userSlice[i].Profile = profileData
`map[int]User`じゃなくて`map[int]*User`にすれば、
`userSlice`の要素を直接いじれるから map -> slice の処理はいらなくなるんじゃない？

2020-08-23 13:52 UTC, akubi0w1 commented on pkg/api/usecase/user/interactor.go
> +			userSlice[i].Profile = profileData
たしかに。。！
というか、`userMap`の定義、`map[int]*User`よな...`UserSlice`って書いてたわ

2020-08-23 14:33 UTC, sana37 commented on pkg/api/response/user.go
> +	Profile  *UserProfile `json:"profile"`
レスポンスでは`Profile`はネストしないで、
そのまま中身のパラメータをフラットに付け加えたい

2020-08-23 14:35 UTC, sana37 commented on pkg/api/response/user.go
> +	Profile  *UserProfile `json:"profile"`
`mail`とか`auth_id`はレスポンスには含めないんじゃない？
ってかAPIドキュメントの修正がまだ終わってなくてごめん、こっちも直すわ！

2020-08-24 07:21 UTC, Takumaron commented on pkg/infrastructure/mysql/profile/repository.go
> +	var userIDsStr []string
めちゃくちゃありがとう！

2020-08-24 09:18 UTC, Takumaron commented on pkg/api/response/user.go
> +	Profile  *UserProfile `json:"profile"`
@sana37 
ちょうど水曜日話そうと思っているんだけれど、grpcに変更になるからRESTのAPIドキュメントは不要になるんよね！
やから、修正も不要です！

2020-08-24 09:19 UTC, Takumaron commented on pkg/api/usecase/user/interactor.go
> +			userSlice[i].Profile = profileData
二人とも有難う！
確かにmapを使った方がシンプルかつ、安全にかけました🎉

2020-08-24 09:21 UTC, Takumaron commented on pkg/api/response/user.go
> +	})
これからboardとかの処理で並び替えが必要になると思うけど、mapを使う以上は並び順を担保してくれない＝実装側でなんとかしないといけないので、sortパッケージを使って改めてソートするというルールにしましょう！

2020-08-24 09:23 UTC, Takumaron commented on pkg/api/response/user.go
> +
@sana37 
こんな感じのレスポンスにして欲しいって認識で合ってるよね？？
```json
[
    {
        "id": 1,
        "auth_id": "fa0571a5-b7f7-4dc8-9baa-a2d6bcf32ab4",
        "user_name": "greading0",
        "mail": "pmccardle0@amazon.co.uk",
        "name": "Corbett",
        "thumbnail": "https://is.gd/consequat/varius/integer/ac/leo.aspx?sollicitudin=imperdiet&vitae=sapien&consectetuer=urna&eget=pretium&rutrum=nisl&at=ut&lorem=volutpat&integer=sapien&tincidunt=arcu&ante=sed&vel=augue&ipsum=aliquam&praesent=erat&blandit=volutpat&lacinia=in&erat=congue&vestibulum=etiam&sed=justo&magna=etiam&at=pretium&nunc=iaculis&commodo=justo&placerat=in&praesent=hac&blandit=habitasse&nam=platea&nulla=dictumst",
        "bio": "0/0",
        "gender": 1,
        "phone": "143-948-7635",
        "place": "in hac",
        "birth": "2014-10-10T00:00:00Z"
    },
    {
        "id": 2,
        "auth_id": "a09e8060-50dc-4efc-8617-b333276dca80",
        "user_name": "breiner1",
        "mail": "rhughill1@bing.com",
        "name": "Amelina",
        "thumbnail": "https://yandex.ru/justo/pellentesque/viverra/pede/ac/diam/cras.js?at=adipiscing&turpis=molestie&a=hendrerit&pede=at&posuere=vulputate&nonummy=vitae&integer=nisl&non=aenean&velit=lectus&donec=pellentesque&diam=eget&neque=nunc&vestibulum=donec&eget=quis&vulputate=orci&ut=eget&ultrices=orci&vel=vehicula&augue=condimentum&vestibulum=curabitur&ante=in&ipsum=libero&primis=ut&in=massa&faucibus=volutpat&orci=convallis&luctus=morbi&et=odio&ultrices=odio&posuere=elementum&cubilia=eu&curae=interdum&donec=eu&pharetra=tincidunt&magna=in&vestibulum=leo&aliquet=maecenas&ultrices=pulvinar&erat=lobortis&tortor=est&sollicitudin=phasellus&mi=sit&sit=amet&amet=erat&lobortis=nulla&sapien=tempus&sapien=vivamus&non=in&mi=felis&integer=eu",
        "bio": "✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿",
        "gender": 2,
        "phone": "436-769-3924",
        "place": "lacus purus",
        "birth": "1984-03-21T00:00:00Z"
    }
]
```

2020-08-24 09:26 UTC, Takumaron commented on pkg/domain/entity/user.go
> +}
entityにUserのmapを定義することで、UserとかUserSliceエンティティと同列で扱えるようにしました！
userIDsを取得するためのメンバ関数も定義してあるので、
```go
userMap.Keys(userMap)
```
でuserIDのArrayが取得できます！

2020-08-24 09:28 UTC, merged